---
title: "Problem Section 1"
date:  "Monday January 13 2025"
graphics: yes
output: pdf_document
header-includes:
    - \usepackage{amsmath, amssymb}
    - \usepackage{framed}\definecolor{shadecolor}{rgb}{0.949,0.949,0.949}
---

```{r setup, include=FALSE}
#use this code chunk to set global options
knitr::opts_chunk$set(echo = TRUE)
```

* * * 

\begin{shaded}

\textbf{Learning Outcomes}

The problems are designed to build conceptual understanding and problem-solving skills. The emphasis is on learning to find, evaluate and build confidence.
The specific tasks include: 

   -  Describe events of interest using set notation.
     
   - Use axioms to calculate probabilities and prove further corollaries.
  
   - Back up and support work with relevant explanations


\end{shaded}

* * *

### Exercises 

1. For each of the following experiments, describe the sample space $S$.

a. Count the number of insect-damaged leaves on a plant.
$$ S = \{ 0,  1, 2, ... , N\} $$
	 
b. Observe the proportion of defectives in a shipment of $N$ electronic components
$$ S = \{ 0, \frac{1}{N}, \frac{2}{N},..., 1\} $$


2. Suppose a person is randomly selected from a large city. Let $A$ be the event that the randomly selected person is male, $B$ the event that the person is under 30 and $C$ that the person speaks French. Write the following verbal description of events using set operations on $A$, $B$, $C$. Venn diagrams might help you to figure out answers to this.  

a. A male at least 30 years old
$$ A \cap B^c$$
$$ A\setminus B$$
	
b. A female under 30 who speaks French
$$ A^c \cap B \cap C $$
	
c. A male who is either under 30 or speaks French
$$ A \cap (B \cup C ) $$
$$ (A\cap B)\cup(A\cap C)$$


3.  Winthrop,a pre-med student, has been summarily rejected by all 126 US medical schools. Desperate,
he sends his transcripts and MCATs to the two least selective foreign schools he can think
of, the two branch campuses (N and E ) of Swampwater Tech. Based on the success his friends have had there,
he estimates that his probability of being accepted at E is 0.7, and at
N, 0.4. He also suspects there is a 75% chance that at least one of his applications
will be rejected. What is the probability that at least one of the schools will accept him?

    Hint: Let $E$ denote the event that he is accepted at the eastern branch and $N$ the event that he is accepted at the Northern branch. You are given $$P(E) = 0.7, P(N) = 0.4, P(E^c \cup N^c) = 0.75.$$ 
You need to find $P(E \cup N).$

### Soltuion
Let $E$ = accepted to eastern and $N$ = accepted to northern so that $P(E)=0.7$ and  $P(N)=0.4$.
We also know that $P(E^c \cup N^c) = P((E\cap N)^c) = 0.75$. 
From this $P(E\cap N)= 1-P((E\cap N)^c) = 1-0.75 = 0.25$.
We want to know $P(E\cup N)$. 
We have that 
$$ P(E\cup N) = P(E) + P(N) - P(E\cap N) $$
which yields $$P(E\cup N) = 0.7+0.4-0.25 = 0.85$$.

4. (Subset inequality) Prove that if $E \subset F$, then $P(E) \leq P(F)$.   (Hint: Write $F$ as the union of two mutually exclusive sets $E$ and $F \setminus E$. )

### Proof
First, note that $F = E\cup (F\setminus E)$.
\begin{align*}
  P(F) &= P(E\cup (F\setminus E)) \\
  &= P(E) + P(F\setminus E)\quad\quad\text{because the probability of any event is positive}\\
  & \geq P(E)
\end{align*}




