---
title: "Problem Section 4"
subtitle:  "Mon February 3"
graphics: yes
output: 
        pdf_document
header-includes:
    - \usepackage{amsmath, amssymb}
    - \usepackage{framed}\definecolor{shadecolor}{rgb}{0.949,0.949,0.949}
    - \usepackage{setspace}
---
\onehalfspacing

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

* * * 
\begin{shaded}

\textbf{Learning Outcomes}

The problems are designed to build conceptual understanding and problem-solving skills. The emphasis is on learning to find, evaluate and build confidence.
The specific tasks include: 

   - Identify whether the conditions for a binomial experiment are satisfied.
     
   - Calculate binomial probabilities
   
   - Calculate expected value
  
   - Back up and support work with relevant explanations


\end{shaded}


* * *

### Exercises 

1. Consider the following random variables. Which ones are binomial? Explain your answer.

a. $X$ is the number of "good" rolls when a die is rolled four times. We call a roll "good" if the number rolled is greater than the roll number. So the first roll is good if it is a 2 or higher. The fourth roll is good if it is a 5 or a 6. 

b. $X$ is the number of tosses for the first head to appear when tossing a coin. You may assume repeated tosses are made in identical fashion 

2. A multiple choice test has 20 questions, each with four answers one of which is correct. Suppose a student randomly guesses the answer to each question. Let the random variable $X$ denote the number of questions they guess correctly. 
  
a. What is the distribution of $X$? State the name of the distribution and also the values of its parameters. Be sure to state (in context) any assumptions you need to make.
  
b. Give an expression for the probability that they will correctly guess 12 questions. Then write the R function for calculating this probability and save it to a variable. Report your answer (rounded to four digits) using inline code.
  
c. How many questions should they *expect* to guess correctly? Write the formula and calculate and report it using inline code **inside the Latex math environment**!
  
d. Give an expression for the probability that they will correctly guess more questions than expected. Then write the R function for calculating this probability and report it using inline code. 

 

3. Weird Wally offers you the following choice. You may have a flat amount of $\frac{1}{3.5}$ dollars or you may roll a fair die and he will give you $\frac{1}{X}$ dollars where $X$ is the value on the roll. 
The PMF of $X$ is shown in the table below.

    \begin{table}[h]
    \centering
    \begin{tabular}{c|c|c|c|c|c|c} \hline
    $x$ & 1& 2 & 3 &4 & 5& 6 \\ \hline
    $f(x)$& $\frac{1}{6}$ & $\frac{1}{6}$ & $\frac{1}{6}$ &$\frac{1}{6}$ &$\frac{1}{6}$     &$\frac{1}{6}$ \\ \hline
    \end{tabular}
    \end{table}

    Which is the better deal? Calculate $E\left[ \frac{1}{X} \right]$ to decide.  (Hint: use the Law of the Unconscious Probabilist - Lemma 7.2)


